### ISSUE TITLE
databricks provider

### ISSUE THREAD

**Issue by mikemowgli** [sllynn/adb-tf-deployment#2]
Thank you for the great stuff in this repo. I'm currently setting up a data lake private endpoint to be consumed by databricks, and your project is relevant.
Just a heads up, once the databricks workspace is created in Azure, it can be tuned with the databricks provider to create additional resources such as a cluster, a secret scope, upload dbfs files, upload notebooks, ...
https://databrickslabs.github.io/databricks-terraform
It's very recent, and still bleeding edge, but helpful already.

**Comment by sllynn** [comment]
Thanks for the feedback. I plan to add some github actions that will automate the deployment of a new workspace on commit (I've done this with Azure DevOps already). The Databricks Terraform provider would be useful to push some 'getting started' materials into a new workspace, I suppose. Shame it can't do Azure Key Vault backed secret scopes yet but I'm sure they're working on it!
